import 'dart:convert';
import 'package:flutter_salesman_module/models/autogenerate_model.dart';
import 'package:flutter_salesman_module/models/token_model.dart';
import 'package:flutter_salesman_module/utils/constants/app_url.dart';
import 'package:http/http.dart' as http;

class LoginApi {
  /// ********************
  /// getLoginToken
  /// ********************
  static Future<UserModel> getLoginToken(
    String username,
    String password,
    String date,
  ) async {
    try {
      String loginUrl = AppUrl.login;

      final headers = {
        'Content-Type': 'application/json',
        'username': username,
        'password': password,
        'date': date,
      };

      final response = await http
          .get(Uri.parse(loginUrl), headers: headers)
          .timeout(const Duration(minutes: 2));

      if (response.statusCode == 200) {
        final data = UserModel.fromJson(json.decode(response.body));

        return data;
      } else if (response.statusCode == 401) {
        throw Exception("401: Invalid username or password");
      } else {
        throw Exception(response.body);
      }
    } catch (error) {
      rethrow;
    }
  }

  static Future<Autogenerated> getChannelData(
    String username,
    String token,
    String date,
    String userId,
  ) async {
    try {
      String loginUrl = "${AppUrl.channelData}?userid=$userId";
      final headers = {
        'Content-Type': 'application/json',
        'username': username,
        'token': token,
        'date': date,
      };

      print("sssssss$date");
      print("sssssss$token");
      print("sssssss$date");
      print("sssssss$userId");

      final response = await http
          .get(Uri.parse(loginUrl), headers: headers)
          .timeout(const Duration(minutes: 2));

      if (response.statusCode == 200) {
        final data = Autogenerated.fromJson(json.decode(response.body));

        return data;
      } else {
        throw Exception(response.body);
      }
    } catch (error) {
      rethrow;
    }
  }
}
