import 'package:flutter_salesman_module/models/channel_data_model.dart';
import 'package:flutter_salesman_module/models/settings_model.dart';
import 'package:flutter_salesman_module/models/watchout_model.dart';

class Autogenerated {
  List<ChannelsData>? channelsData;
  WatchoutData? watchoutData;
  Settings? settings;

  Autogenerated({this.channelsData, this.watchoutData, this.settings});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      channelsData:
          json['ChannelsData'] != null
              ? List<ChannelsData>.from(
                json['ChannelsData'].map((v) => ChannelsData.fromJson(v)),
              )
              : null,
      watchoutData:
          json['WatchoutData'] != null
              ? WatchoutData.fromJson(json['WatchoutData'])
              : null,
      settings:
          json['Settings'] != null ? Settings.fromJson(json['Settings']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      if (channelsData != null)
        'ChannelsData': channelsData!.map((v) => v.toJson()).toList(),
      if (watchoutData != null) 'WatchoutData': watchoutData!.toJson(),
      if (settings != null) 'Settings': settings!.toJson(),
    };
  }
}
